<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductGallery;
use App\Models\ProductSpecification;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $products = [

            [
                'name' => 'TechSync ChronoPro X: Precision Digital Watch',
                'slug' => Str::slug('TechSync ChronoPro X: Precision Digital Watch'),
                'sku' => 'DW2023M',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'TechSync ChronoPro X, a cutting-edge digital watch designed for the contemporary adventurer. This high-performance timepiece seamlessly combines.',
                'long_desc' => '<p>Key Features:</p><p><span style="font-size: 1rem;"><b>Precision Timekeeping:</b> The ChronoPro X is equipped with state-of-the-art quartz movement, ensuring unparalleled accuracy in timekeeping. Whether you'.'re navigating the urban jungle or embarking on a wilderness expedition, trust the precision of TechSync.</span><br></p><p><span style="font-size: 1rem;"><b>Digital Display Excellence:</b> The vibrant LCD display offers crystal-clear visibility, presenting time, date, and additional features with sharp clarity. Effortlessly toggle between various functions using the intuitive interface.</span><br></p><p><span style="font-size: 1rem;"><b>Rugged Durability:</b> Engineered for durability, the ChronoPro X boasts a robust yet lightweight construction. The scratch-resistant mineral crystal and water-resistant design make it a reliable companion for any environment.</span><br></p><p><span style="font-size: 1rem;"><b>Smart Functionality:</b> Stay connected and organized with smart features such as alarms, stopwatch, and a backlight for low-light conditions. The watch also includes a calendar function, ensuring you'.'re well-prepared for every occasion.</span><br></p><p><span style="font-size: 1rem;"><b>Sleek Design:</b> The modern design of the ChronoPro X combines form and function seamlessly. The sleek profile, complemented by a stainless steel case and comfortable silicone strap, makes it suitable for both formal and casual settings.</span><br></p><p><span style="font-size: 1rem;"><b>Long-lasting Battery Life:</b> Say goodbye to frequent charging. The ChronoPro X is engineered for efficiency, providing extended battery life to keep up with your dynamic lifestyle.</span><br></p>',
                'category_id' => 2,
                'features_image' => '1-1702299064.jpg',
                'sale_type' => 2,
                'schedule_type' => 2,
                'min_deposit' => 50,
                'min_deposit_type' => 1,
                'quantity' => 40,
                'price' => 750.0,
                'sale_price' => 450.0,
                'min_bid_price' => null,
                'start_date' => null,
                'end_date' => null,
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'HyperGrip Pro Gaming Pad',
                'slug' => Str::slug('HyperGrip Pro Gaming Pad'),
                'sku' => 'GP2026A',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'HyperGrip Pro, the ultimate game pad designed to elevate your gaming experience to new heights. Engineered for precision, comfort, and versatility.',
                'long_desc' => '<p><b>Key Features:</b></p><p><span style="font-size: 1rem;"><b>Responsive Precision:</b></span><br></p><p><span style="font-size: 1rem;">The HyperGrip Pro boasts ultra-responsive buttons and analog sticks, providing gamers with unparalleled control and accuracy. Every press and movement translates seamlessly into the virtual world, giving you the edge in fast-paced action.</span><br></p><p><b>Ergonomic Design:</b></p><p><span style="font-size: 1rem;">Say goodbye to hand fatigue with the ergonomic design of the HyperGrip Pro. Comfort is king, and this game pad is sculpted to fit naturally in your hands, ensuring extended gaming sessions without discomfort.</span><br></p><p><b>Customizable Controls:</b></p><p><span style="font-size: 1rem;">Tailor the game pad to your playstyle with customizable controls. Easily remap buttons and adjust sensitivity to match the demands of different games, putting the power of customization at your fingertips.</span><br></p><p><b>Versatile Compatibility:</b></p><p><span style="font-size: 1rem;">The HyperGrip Pro is designed for universal compatibility, seamlessly connecting to a variety of gaming platforms, including PC, consoles, and mobile devices. Enjoy the same exceptional performance across all your gaming devices.</span><br></p><p><b>Wireless Freedom:</b></p><p><span style="font-size: 1rem;">Cut the cords and enjoy wireless freedom with the HyperGrip Pro. Whether you'.'re lounging on the couch or engaging in an intense gaming session at your desk, the wireless connectivity ensures a hassle-free and immersive experience.</span><br></p><p><b>Immersive Feedback:</b></p><p><span style="font-size: 1rem;">Feel the action with immersive haptic feedback. The HyperGrip Pro provides tactile sensations that enhance your gaming experience, allowing you to feel every explosion, hit, or subtle nuance within the game.</span><br></p><p><b>Stylish Aesthetics:</b></p><p><span style="font-size: 1rem;">Elevate your gaming setup with the sleek and stylish design of the HyperGrip Pro. Backlit buttons add a futuristic touch, while the overall aesthetic reflects the cutting-edge technology packed into this high-performance game pad.</span><br></p>',
                'category_id' => 7,
                'features_image' => '7-1702302730.jpg',
                'sale_type' => 2,
                'schedule_type' => 2,
                'min_deposit' => 0,
                'min_deposit_type' => 1,
                'quantity' => 40,
                'price' => 500.0,
                'sale_price' => 600.0,
                'min_bid_price' => null,
                'start_date' => null,
                'end_date' => null,
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Essentials Harmony Elevate Your Home',
                'slug' => Str::slug('Essentials Harmony Elevate Your Home'),
                'sku' => 'HS2234G',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'A suite of meticulously crafted household products designed to seamlessly integrate into your daily routine, bringing efficiency.',
                'long_desc' => '<p><b>Effortless Cleaning with Radiance Broom:</b></p><p><span style="font-size: 1rem;">The Radiance Broom isn'.'t just a cleaning tool; it'.'s a household hero. Crafted with precision bristles and an ergonomic handle, it effortlessly sweeps away dirt, leaving your floors gleaming. Embrace the joy of efficient cleaning with this essential household companion.</span><br></p><p><b>Culinary Mastery with CulinaChef Knife Set:</b></p><p><span style="font-size: 1rem;">Unleash your inner chef with the CulinaChef Knife Set. Precision-engineered blades meet ergonomic handles for a perfect balance of form and function. Elevate your culinary creations and make every meal preparation a work of art.</span><br></p><p><b>Laundry Bliss with FreshGlow Fabric Softener:</b></p><p><span style="font-size: 1rem;">Transform your laundry routine with FreshGlow Fabric Softener. Indulge in the luxurious softness it brings to your clothes while enjoying the invigorating fragrance that lingers. Rediscover the joy of wearing garments that feel as good as they look.</span><br></p><p><b>Smart Storage with SpaceSaver Organizers:</b></p><p><span style="font-size: 1rem;">Tame the clutter and reclaim your space with SpaceSaver Organizers. These sleek, stackable wonders maximize storage efficiency, turning chaotic spaces into organized sanctuaries. Experience the liberation of a tidy home without compromising on style.</span><br></p><p><b>Revolutionize Cleaning with PureMist Cleaning Spray:</b></p><p><span style="font-size: 1rem;">Introducing PureMist Cleaning Spray, a game-changer in household cleaning. This eco-friendly powerhouse effortlessly tackles grime and germs, leaving surfaces sparkling clean and your home smelling fresh. Embrace the future of clean with this essential addition to your cleaning arsenal.</span><br></p><p><b>Tranquil Ambiance with ZenAura Oil Diffuser:</b></p><p><span style="font-size: 1rem;">Transform your living space into a haven of tranquility with the ZenAura Oil Diffuser. Elegant design meets therapeutic functionality, providing a soothing ambiance with your favorite essential oils. Elevate your home environment with this serene addition.</span><br></p>',
                'category_id' => 4,
                'features_image' => '3-1702311850.jpg',
                'sale_type' => 2,
                'schedule_type' => 2,
                'min_deposit' => 0,
                'min_deposit_type' => 1,
                'quantity' => 100,
                'price' => 750.00,
                'sale_price' => 550.00,
                'min_bid_price' => 0,
                'start_date' => null ,
                'end_date' =>null,
                'status' => 1,

                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Creative Fashion Riboon Digital Watch Little Elegant.',
                'slug' => Str::slug('Creative Fashion Riboon Digital Watch Little Elegant'),
                'sku' => 'CF2024TA',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'Transform your living space into a haven of comfort and style with our curated collection of household stuffs. From everyday essentials to innovative gadgets, we have everything you need to make your home a sanctuary of functionality and aesthetics.',
                'long_desc' => '<h4 style=""><font color="#1f2230" face="Saira, sans-serif">Key Features:</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Quality and Durability: Our household stuffs are crafted with precision and durability in mind. Discover a range of products made from high-quality materials that stand the test of time, ensuring longevity in every item.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Stylish and Trendy Designs: Elevate your home decor with our stylish and trendy designs. Whether yourelooking for modern minimalism, classic elegance, or eclectic charm, our collection has something to complement every taste and style.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Smart Home Solutions: Embrace the future of living with our smart home solutions. From intelligent lighting and home automation to innovative kitchen gadgets, experience the convenience of technology seamlessly integrated into your daily life.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Organization and Storage: Declutter and organize your living space with our smart storage solutions. Explore a variety of organizers, storage bins, and space-saving furniture designed to maximize efficiency without compromising on style.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Comfortable Living: Create a cozy and inviting atmosphere with our range of comfort-focused household items. From plush cushions and throws to ergonomic furniture, prioritize comfort without sacrificing aesthetic appeal.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Eco-Friendly Options: Join the movement towards sustainability with our eco-friendly household products. Choose from a selection of environmentally conscious items that contribute to a greener and healthier planet.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Budget-Friendly Choices: Enjoy quality without breaking the bank. Our household collection offers budget-friendly options without compromising on functionality or&nbsp;</font></h4><ul class="describe-list" style="padding: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; list-style: none; font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"></ul>',
                'category_id' => 1,
                'features_image' => 'prod-gallery3-1683461599.png',
                'sale_type' => 1,
                'schedule_type' => 1,
                'min_deposit' => 50,
                'min_deposit_type' => 1,
                'quantity' => 100,
                'price' => null,
                'sale_price' => null,
                'min_bid_price' => 30,
                'start_date' => '2024-09-07 00:00:00',
                'end_date' => '2030-12-08 23:00:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Digital Pen Watch Little Elegant.',
                'slug' => Str::slug('Digital Pen Watch Little Elegant'),
                'sku' => 'DP2024TR',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'Transform your living space into a haven of comfort and style with our curated collection of household stuffs. From everyday essentials to innovative gadgets, we have everything you need to make your home a sanctuary of functionality and aesthetics.',
                'long_desc' => '<h4 style=""><font color="#1f2230" face="Saira, sans-serif">Key Features:</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Quality and Durability: Our household stuffs are crafted with precision and durability in mind. Discover a range of products made from high-quality materials that stand the test of time, ensuring longevity in every item.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Stylish and Trendy Designs: Elevate your home decor with our stylish and trendy designs. Whether yourelooking for modern minimalism, classic elegance, or eclectic charm, our collection has something to complement every taste and style.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Smart Home Solutions: Embrace the future of living with our smart home solutions. From intelligent lighting and home automation to innovative kitchen gadgets, experience the convenience of technology seamlessly integrated into your daily life.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Organization and Storage: Declutter and organize your living space with our smart storage solutions. Explore a variety of organizers, storage bins, and space-saving furniture designed to maximize efficiency without compromising on style.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Comfortable Living: Create a cozy and inviting atmosphere with our range of comfort-focused household items. From plush cushions and throws to ergonomic furniture, prioritize comfort without sacrificing aesthetic appeal.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Eco-Friendly Options: Join the movement towards sustainability with our eco-friendly household products. Choose from a selection of environmentally conscious items that contribute to a greener and healthier planet.</font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif"><br></font></h4><h4 style=""><font color="#1f2230" face="Saira, sans-serif">Budget-Friendly Choices: Enjoy quality without breaking the bank. Our household collection offers budget-friendly options without compromising on functionality or&nbsp;</font></h4><ul class="describe-list" style="padding: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; list-style: none; font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"></ul>',
                'category_id' => 1,
                'features_image' => 'prod-gallery1-1683454861.png',
                'sale_type' => 1,
                'schedule_type' => 1,
                'min_deposit' => 50,
                'min_deposit_type' => 1,
                'quantity' => 100,
                'price' => null,
                'sale_price' => null,
                'min_bid_price' => 250.00,
                'start_date' => '2024-09-20 00:00:00',
                'end_date' => '2023-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Antique Products To Explore History.',
                'slug' => Str::slug('Antique Products To Explore History'),
                'sku' => 'BP2023HK',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'Indulge in the luxury of our Radiant Glow Skincare Set, a meticulously curated collection of beauty products designed to nourish, rejuvenate, and enhance your natural beauty. Crafted with precision and infused with the finest ingredients, this set is your ultimate companion for a radiant and flawless complexion.',
                'long_desc' => '<p>Key Features:</p><p><br></p><p>Revitalizing Cleanser:</p><p>Begin your skincare ritual with our gentle yet effective revitalizing cleanser. Enriched with botanical extracts and antioxidants, it effortlessly removes impurities, leaving your skin refreshed and ready for the next steps.</p><p><br></p><p>Hydrating Facial Toner:</p><p>Our hydrating facial toner is a burst of hydration for your skin. Formulated with floral waters and essential nutrients, it restores the skinspH balance, prepping it for optimal absorption of subsequent skincare products.</p><p><br></p><p>Nourishing Day Cream:</p><p>Experience the embrace of our nourishing day cream, a lightweight and hydrating formula that provides all-day moisture. Packed with vitamins and SPF protection, it defends your skin against environmental stressors while leaving it silky smooth.</p><p><br></p><p>Rejuvenating Night Serum:</p><p>Unwind with our rejuvenating night serum, a potent elixir that works while you sleep. Infused with anti-aging ingredients, it helps reduce fine lines and promotes cell renewal, revealing a more youthful and radiant complexion by morning.</p><p><br></p><p>Eye Brightening Treatment:</p><p>Banish signs of fatigue with our eye brightening treatment. Specially formulated for the delicate eye area, it reduces puffiness, minimizes dark circles, and revitalizes tired eyes for a refreshed and awakened look.</p><p><br></p><p>Pampering Face Mask:</p><p>Treat yourself to a spa-like experience with our pampering face mask. Formulated with natural clays and botanical extracts, it detoxifies, hydrates, and leaves your skin feeling luxuriously soft and revitalized.</p>',
                'category_id' => 3,
                'features_image' => '6-1702365568.jpg',
                'sale_type' => 1,
                'schedule_type' => 1,
                'min_deposit' => 50,
                'min_deposit_type' => 1,
                'quantity' => 100,
                'price' => null,
                'sale_price' => null,
                'min_bid_price' => 500.00,
                'start_date' => '2023-11-28 21:24:00',
                'end_date' => '2030-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Historical Elements of Stone Era.',
                'slug' => Str::slug('Historical Elements of Stone Era'),
                'sku' => 'BP2023HK',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'The Digital Arts Masterpieces Collection captivates with its intricate details. Zoom in, and you'.'ll discover a level of precision that brings every stroke and nuance to life.',
                'long_desc' => '<p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Key Features</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder; font-size: 1rem;">Unparalleled Detail:</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">The Digital Arts Masterpieces Collection captivates with its intricate details. Zoom in, and you'.'ll discover a level of precision that brings every stroke and nuance to life, creating an immersive experience for art enthusiasts.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Technicolor Dreams:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">Immerse yourself in a kaleidoscope of colors that span the spectrum of human emotion. From vibrant bursts of energy to subtle gradients that evoke tranquility, each digital painting is a testament to the artist'.'s mastery of the digital palette.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Diverse Styles:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">Explore a diverse range of artistic styles, from hyper-realistic renderings to abstract expressions of emotion. The collection celebrates the versatility of digital art, showcasing the artist'.'s ability to transcend traditional boundaries.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Imaginative Themes:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">Journey through a gallery of imaginative themes that transport you to different worlds. Whether it'.'s futuristic cityscapes, enchanting fantasy realms, or poignant portraits, each painting tells a unique story and invites viewers to interpret the narrative in their own way.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">High-Resolution Quality:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">Every digital painting in this collection is presented in stunning high resolution, ensuring that the depth and richness of the artwork are preserved. Witness the details come alive, making it an ideal choice for both digital displays and fine art prints.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Tech-Meets-Art:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">The Digital Arts Masterpieces Collection celebrates the harmonious marriage of technology and artistry. Each piece is a testament to the limitless possibilities that digital tools bring to the creative process, pushing the boundaries of what is visually achievable.</span></p>',
                'category_id' => 3,
                'features_image' => '2-1702365648.jpg',
                'sale_type' => 1,
                'schedule_type' => 1,
                'min_deposit' => 100,
                'min_deposit_type' => 2,
                'quantity' => 100,
                'price' => null,
                'sale_price' => null,
                'min_bid_price' => 500.00,
                'start_date' => '2023-11-28 21:24:00',
                'end_date' => '2030-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elegance Defined: Serenity Chic Leather.',
                'slug' => Str::slug('Elegance Defined: Serenity Chic Leather'),
                'sku' => 'LP2267W',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'Serenity Chic Leather Tote, a sophisticated and versatile accessory designed to complement the lifestyle of the modern woman. Crafted with meticulous.',
                'long_desc' => '<p><b>Material: Luxurious Leather</b></p><p><span style="font-size: 1rem;">The Serenity Chic Tote is meticulously crafted from high-quality, genuine leather, ensuring a soft, supple feel and a timeless aesthetic that only improves with age.</span><br></p><p><b>Design: Timeless Elegance</b></p><p><span style="font-size: 1rem;">The purse features a sleek and minimalist design, accented with subtle details that exude sophistication. Its classic silhouette makes it suitable for both casual outings and formal events, adding a touch of timeless elegance to any ensemble.</span><br></p><p><b>Spacious Interior:</b></p><p><span style="font-size: 1rem;">Stay organized with a spacious and well-organized interior. Multiple compartments, including zippered pockets and dedicated slots for essentials like keys and cards, ensure everything has its place.</span><br></p><p><b>Versatile Carry Options:</b></p><p><span style="font-size: 1rem;">The Serenity Chic Tote offers versatile carrying options. Choose between the sturdy top handles for a classic look or the detachable, adjustable shoulder strap for hands-free convenience.</span><br></p><p><b>Secure Closure:</b></p><p><span style="font-size: 1rem;">The purse is equipped with a secure and stylish closure mechanism, keeping your belongings safe while adding a touch of flair to the overall design.</span><br></p>',
                'category_id' => 2,
                'features_image' => '7-1702301597.jpg',
                'sale_type' => 1,
                'schedule_type' => 2,
                'min_deposit' => 100,
                'min_deposit_type' => 2,
                'quantity' => 100,
                'price' => 350.0,
                'sale_price' => 500.0,
                'min_bid_price' => 500.00,
                'start_date' => '2024-06-26 21:24:00',
                'end_date' => '2030-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luminance Dreams: Digital Art Canvas Collection.',
                'slug' => Str::slug('Luminance Dreams: Digital Art Canvas Collection'),
                'sku' => 'LD2024CS',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'Digital Arts Masterpieces Collection, a captivating series of digital paintings that redefine the boundaries of artistic expression.',
                'long_desc' => '<p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Key Features:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder; font-size: 1rem;">Unparalleled Detail:</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">The Digital Arts Masterpieces Collection captivates with its intricate details. Zoom in, and you'.'ll discover a level of precision that brings every stroke and nuance to life, creating an immersive experience for art enthusiasts.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Technicolor Dreams:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">Immerse yourself in a kaleidoscope of colors that span the spectrum of human emotion. From vibrant bursts of energy to subtle gradients that evoke tranquility, each digital painting is a testament to the artist'.'s mastery of the digital palette.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Diverse Styles:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">Explore a diverse range of artistic styles, from hyper-realistic renderings to abstract expressions of emotion. The collection celebrates the versatility of digital art, showcasing the artist'.'s ability to transcend traditional boundaries.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Imaginative Themes:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">Journey through a gallery of imaginative themes that transport you to different worlds. Whether it'.'s futuristic cityscapes, enchanting fantasy realms, or poignant portraits, each painting tells a unique story and invites viewers to interpret the narrative in their own way.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">High-Resolution Quality:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">Every digital painting in this collection is presented in stunning high resolution, ensuring that the depth and richness of the artwork are preserved. Witness the details come alive, making it an ideal choice for both digital displays and fine art prints.</span><br></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-weight: bolder;">Tech-Meets-Art:</span></p><p style="margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="font-size: 1rem;">The Digital Arts Masterpieces Collection celebrates the harmonious marriage of technology and artistry. Each piece is a testament to the limitless possibilities that digital tools bring to the creative process, pushing the boundaries of what is visually achievable.</span></p>',
                'category_id' => 6,
                'features_image' => '7-1702302422.jpg',
                'sale_type' => 1,
                'schedule_type' => 2,
                'min_deposit' => 200,
                'min_deposit_type' => 2,
                'quantity' => 100,
                'price' => 3000.00,
                'sale_price' => 4500.0,
                'min_bid_price' => 4500.0,
                'start_date' => '2024-03-26 19:47:02',
                'end_date' => '2026-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SwiftSync Precision Wireless Mouse.',
                'slug' => Str::slug('SwiftSync Precision Wireless Mouse'),
                'sku' => 'WM2303M',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'SwiftSync Precision Wireless Mouse, a technological marvel that redefines the way you navigate your digital world. Seamlessly blending precision.',
                'long_desc' => '<p><b>Wireless Freedom:</b></p><p><span style="font-size: 1rem;">Break free from the constraints of cables and enjoy the freedom to move with the SwiftSync Precision Wireless Mouse. Its advanced wireless technology ensures a stable and responsive connection, allowing you to work or game with ease from anywhere in the room.</span><br></p><p><b>Precision Tracking:</b></p><p><span style="font-size: 1rem;">Navigate with confidence using the SwiftSync'.'s precision tracking technology. Whether you'.'re editing documents, designing graphics, or gaming, experience smooth and accurate cursor control for enhanced productivity and performance.</span><br></p><p><b>Ergonomic Comfort:</b></p><p><span style="font-size: 1rem;">Designed with your comfort in mind, the SwiftSync Precision Wireless Mouse features an ergonomic shape that fits naturally in your hand. Say goodbye to discomfort during long hours of use and hello to a mouse that supports your hand'.'s natural contours.</span><br></p><p><b>Effortless Scrolling:</b></p><p><span style="font-size: 1rem;">Effortlessly scroll through web pages, documents, and spreadsheets with the SwiftSync'.'s responsive scroll wheel. The tactile feedback ensures a satisfying and intuitive scrolling experience for efficient navigation.</span><br></p><p><b>Customizable Buttons:</b></p><p><span style="font-size: 1rem;">Tailor the mouse to your preferences with customizable buttons. Assign frequently used functions to the programmable buttons for quick access, streamlining your workflow and giving you</span><br></p>',
                'category_id' => 7,
                'features_image' => '8-1702303074.jpg',
                'sale_type' => 1,
                'schedule_type' => 2,
                'min_deposit' => 20,
                'min_deposit_type' => 2,
                'quantity' => 100,
                'price' => 500.00,
                'sale_price' => 550.00,
                'min_bid_price' => 200.0,
                'start_date' => '2024-01-26 18:13:00',
                'end_date' => '2027-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tyota Horizon X: Elevate.',
                'slug' => Str::slug('Tyota Horizon X: Elevate'),
                'sku' => 'Tyc2023A',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'Tyota Horizon X -This exceptional car seamlessly blends cutting-edge technology, unparalleled performance, and sophisticated design, offering a driving experience like no other.',
                'long_desc' => '<p><b>Key Features:</b></p><p><span style="font-size: 1rem;"><b>Dynamic Performance:</b> The Tyota Horizon X is engineered for exhilarating performance, powered by a state-of-the-art engine that delivers a perfect balance of power and fuel efficiency. Whether navigating city streets or cruising on the open highway, experience driving at its finest.</span><br></p><p><span style="font-size: 1rem;"><b>Smart Connectivity:</b> Stay seamlessly connected with the intuitive infotainment system. The Tyota Horizon X features advanced connectivity options, including Apple CarPlay and Android Auto, ensuring that you can access your favorite apps, music, and navigation with ease.</span><br></p><p><span style="font-size: 1rem;"><b>Safety Redefined:</b> Tyota prioritizes your safety with a comprehensive suite of advanced safety features. From adaptive cruise control to lane departure warning, the Horizon X is equipped to keep you and your passengers safe on every journey.</span><br></p><p><span style="font-size: 1rem;"><b>Luxurious Interior:</b> Step inside the cabin, where comfort meets elegance. The Tyota Horizon X boasts a meticulously designed interior with premium materials, ergonomic seating, and thoughtful details that elevate your driving experience.</span><br></p><p><span style="font-size: 1rem;"><b>Sleek Exterior Design</b>: Make a statement on the road with the Tyota Horizon X'.'s sleek and aerodynamic exterior. The modern design, stylish contours, and signature Tyota grille combine to create a car that turns heads wherever you go.</span><br></p><p><span style="font-size: 1rem;"><b>Efficiency at Its Core: </b>Embrace eco-friendly driving without compromising performance. The Tyota Horizon X incorporates advanced technologies to maximize fuel efficiency and minimize environmental impact, ensuring a responsible and sustainable driving experience.</span><br></p><p><span style="font-size: 1rem;"><b>Innovative Technology:</b> Tyota doesn'.'t just keep up with the times; it sets the standard. The Horizon X features the latest in automotive technology, from a responsive touchscreen display to voice-activated controls, making every drive a seamless and enjoyable experience.</span><br></p>',
                'category_id' => 5,
                'features_image' => '3-1702300198.jpg',
                'sale_type' => 1,
                'schedule_type' => 1,
                'min_deposit' => 1000,
                'min_deposit_type' => 2,
                'quantity' => 100,
                'price' => 25000.00,
                'sale_price' => 30000.00,
                'min_bid_price' => 30000.00,
                'start_date' => '2023-12-30 06:00:00',
                'end_date' => '2027-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BMW 2022 Unleash the Ultimate Driving.',
                'slug' => Str::slug('BMW 2022 Unleash the Ultimate Driving'),
                'sku' => 'BM2026C',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'This exceptional car seamlessly blends cutting-edge technology, unparalleled performance, and sophisticated design, offering a driving experience like no other.',
                'long_desc' => '<p><span style="font-weight: bolder;">Key Features:</span></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Dynamic Performance:</span>&nbsp;The Tyota Horizon X is engineered for exhilarating performance, powered by a state-of-the-art engine that delivers a perfect balance of power and fuel efficiency. Whether navigating city streets or cruising on the open highway, experience driving at its finest.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Smart Connectivity:</span>&nbsp;Stay seamlessly connected with the intuitive infotainment system. The Tyota Horizon X features advanced connectivity options, including Apple CarPlay and Android Auto, ensuring that you can access your favorite apps, music, and navigation with ease.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Safety Redefined:</span>&nbsp;Tyota prioritizes your safety with a comprehensive suite of advanced safety features. From adaptive cruise control to lane departure warning, the Horizon X is equipped to keep you and your passengers safe on every journey.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Luxurious Interior:</span>&nbsp;Step inside the cabin, where comfort meets elegance. The Tyota Horizon X boasts a meticulously designed interior with premium materials, ergonomic seating, and thoughtful details that elevate your driving experience.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Sleek Exterior Design</span>: Make a statement on the road with the Tyota Horizon X'.'s sleek and aerodynamic exterior. The modern design, stylish contours, and signature Tyota grille combine to create a car that turns heads wherever you go.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Efficiency at Its Core:&nbsp;</span>Embrace eco-friendly driving without compromising performance. The Tyota Horizon X incorporates advanced technologies to maximize fuel efficiency and minimize environmental impact, ensuring a responsible and sustainable driving experience.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Innovative Technology:</span>&nbsp;Tyota doesn'.'t just keep up with the times; it sets the standard. The Horizon X features the latest in automotive technology, from a responsive touchscreen display to voice-activated controls, making every drive a seamless and enjoyable experience.</span></p>',
                'category_id' => 5,
                'features_image' => '4-1702366330.jpg',
                'sale_type' => 1,
                'schedule_type' => 1,
                'min_deposit' => 1000,
                'min_deposit_type' => 2,
                'quantity' => 100,
                'price' => 15000.00,
                'sale_price' => 17000.00,
                'min_bid_price' => 17000.00,
                'start_date' => '2023-12-30 06:00:00',
                'end_date' => '2027-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vivid Canvas: Digital Arts Masterpieces Collection.',
                'slug' => Str::slug('Vivid Canvas: Digital Arts Masterpieces Collection'),
                'sku' => 'DA2025TC',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'This exceptional car seamlessly blends cutting-edge technology, unparalleled performance, and sophisticated design, offering a driving experience like no other.',
                'long_desc' => '<p><span style="font-weight: bolder;">Key Features:</span></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Dynamic Performance:</span>&nbsp;The Tyota Horizon X is engineered for exhilarating performance, powered by a state-of-the-art engine that delivers a perfect balance of power and fuel efficiency. Whether navigating city streets or cruising on the open highway, experience driving at its finest.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Smart Connectivity:</span>&nbsp;Stay seamlessly connected with the intuitive infotainment system. The Tyota Horizon X features advanced connectivity options, including Apple CarPlay and Android Auto, ensuring that you can access your favorite apps, music, and navigation with ease.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Safety Redefined:</span>&nbsp;Tyota prioritizes your safety with a comprehensive suite of advanced safety features. From adaptive cruise control to lane departure warning, the Horizon X is equipped to keep you and your passengers safe on every journey.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Luxurious Interior:</span>&nbsp;Step inside the cabin, where comfort meets elegance. The Tyota Horizon X boasts a meticulously designed interior with premium materials, ergonomic seating, and thoughtful details that elevate your driving experience.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Sleek Exterior Design</span>: Make a statement on the road with the Tyota Horizon X'.'s sleek and aerodynamic exterior. The modern design, stylish contours, and signature Tyota grille combine to create a car that turns heads wherever you go.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Efficiency at Its Core:&nbsp;</span>Embrace eco-friendly driving without compromising performance. The Tyota Horizon X incorporates advanced technologies to maximize fuel efficiency and minimize environmental impact, ensuring a responsible and sustainable driving experience.</span><br></p><p><span style="font-size: 1rem;"><span style="font-weight: bolder;">Innovative Technology:</span>&nbsp;Tyota doesn'.'t just keep up with the times; it sets the standard. The Horizon X features the latest in automotive technology, from a responsive touchscreen display to voice-activated controls, making every drive a seamless and enjoyable experience.</span></p>',
                'category_id' => 4,
                'features_image' => '1-1702301913.jpg',
                'sale_type' => 1,
                'schedule_type' => 1,
                'min_deposit' => 20,
                'min_deposit_type' => 1,
                'quantity' => 100,
                'price' => 5000.00,
                'sale_price' => 5500.00,
                'min_bid_price' => 5500.00,
                'start_date' => '2023-12-30 06:00:00',
                'end_date' => '2027-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stand Table To Set Accesorries.',
                'slug' => Str::slug('Stand Table To Set Accesorries'),
                'sku' => 'ST2033A',
                'meta_title' => null,
                'meta_keyward' => null,
                'meta_description' => null,
                'author_id' => 2,
                'short_desc' => 'The Radiance Broom isn'.'t just a cleaning tool; it'.'s a household hero. Crafted with precision bristles and an ergonomic handle, it effortlessly sweeps away dirt, leaving your floors gleaming.',
                'long_desc' => '<p><b>Effortless Cleaning with Radiance Broom:</b></p><p><span style="font-size: 1rem;">The Radiance Broom isn'.'t just a cleaning tool; it'.'s a household hero. Crafted with precision bristles and an ergonomic handle, it effortlessly sweeps away dirt, leaving your floors gleaming. Embrace the joy of efficient cleaning with this essential household companion.</span><br></p><p><b>Culinary Mastery with CulinaChef Knife Set:</b></p><p><span style="font-size: 1rem;">Unleash your inner chef with the CulinaChef Knife Set. Precision-engineered blades meet ergonomic handles for a perfect balance of form and function. Elevate your culinary creations and make every meal preparation a work of art.</span><br></p><p><b>Laundry Bliss with FreshGlow Fabric Softener:</b></p><p><span style="font-size: 1rem;">Transform your laundry routine with FreshGlow Fabric Softener. Indulge in the luxurious softness it brings to your clothes while enjoying the invigorating fragrance that lingers. Rediscover the joy of wearing garments that feel as good as they look.</span><br></p><p><b>Smart Storage with SpaceSaver Organizers:</b></p><p><span style="font-size: 1rem;">Tame the clutter and reclaim your space with SpaceSaver Organizers. These sleek, stackable wonders maximize storage efficiency, turning chaotic spaces into organized sanctuaries. Experience the liberation of a tidy home without compromising on style.</span><br></p><p><b>Revolutionize Cleaning with PureMist Cleaning Spray:</b></p><p><span style="font-size: 1rem;">Introducing PureMist Cleaning Spray, a game-changer in household cleaning. This eco-friendly powerhouse effortlessly tackles grime and germs, leaving surfaces sparkling clean and your home smelling fresh. Embrace the future of clean with this essential addition to your cleaning arsenal.</span><br></p><p><b>Tranquil Ambiance with ZenAura Oil Diffuser:</b></p><p><span style="font-size: 1rem;">Transform your living space into a haven of tranquility with the ZenAura Oil Diffuser. Elegant design meets therapeutic functionality, providing a soothing ambiance with your favorite essential oils. Elevate your home environment with this serene addition.</span><br></p>',
                'category_id' => 4,
                'features_image' => '2-1702312154.jpg',
                'sale_type' => 1,
                'schedule_type' => 1,
                'min_deposit' => 200,
                'min_deposit_type' => 2,
                'quantity' => 1,
                'price' => 1500.00,
                'sale_price' => 2000.00,
                'min_bid_price' => 700.00,
                'start_date' => '2025-12-30 06:00:00',
                'end_date' => '2027-12-31 23:59:00',
                'status' => 1,
                'enable_seo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        if (Product::count() == 0) {
            Product::insert($products);
        }

        $specifications = [

            [
                'label' => 'Color',
                'value' => 'Yellow, Blue, Purple',
                'product_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Size',
                'value' => 'Medium',
                'product_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Brand',
                'value' => 'Riboon',
                'product_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'label' => 'Color',
                'value' => 'Blue',
                'product_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Size',
                'value' => 'Medium',
                'product_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Brand',
                'value' => 'Riboon',
                'product_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'label' => 'Color',
                'value' => 'red',
                'product_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Size',
                'value' => 'Medium',
                'product_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Brand',
                'value' => 'Riboon',
                'product_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'label' => 'Color',
                'value' => 'Black',
                'product_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Waterproof',
                'value' => 'Yes',
                'product_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Skin',
                'value' => 'Lather',
                'product_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'label' => 'Design',
                'value' => 'Elegance',
                'product_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Material',
                'value' => 'Luxurious Leather',
                'product_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Color',
                'value' => 'White',
                'product_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'label' => 'Paint',
                'value' => 'Canvas',
                'product_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Color',
                'value' => 'Water Color',
                'product_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Wire Model',
                'value' => 'Wireless',
                'product_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Battery',
                'value' => 'Long Durability',
                'product_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Function',
                'value' => 'Wireless',
                'product_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Made With',
                'value' => 'Ceramic',
                'product_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Design',
                'value' => 'Unique',
                'product_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Age',
                'value' => '500Yrs',
                'product_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'label' => 'Engine',
                'value' => 'Twin-turbocharged V6',
                'product_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Suspension',
                'value' => 'Independent McPherson struts',
                'product_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Wheels',
                'value' => '18 inches (alloy wheels)',
                'product_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Color',
                'value' => 'Multicolor',
                'product_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Engine:',
                'value' => 'Twin-turbocharged V6',
                'product_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Suspension:',
                'value' => 'Independent McPherson struts',
                'product_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'label' => 'Brake',
                'value' => 'Ventilated disc brakes',
                'product_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        if (ProductSpecification::count() == 0) {
            ProductSpecification::insert($specifications);
        }

        $galleries = [
            [
                'product_id' => 1,
                'image' => 'prod-gallery2-1683454862.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'image' => 'prod-gallery3-1683454862.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'image' => 'prod-gallery2-1683454862-1703665324-1703665539.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'image' => 'prod-gallery3-1683461599-1703665539.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'image' => '2-1702364321.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'image' => '3-1702364321.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'image' => '6-1702364321.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'image' => '2-1702365542.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'image' => '3-1702365542.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'image' => '4-1702365542.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'product_id' => 5,
                'image' => '2-1702300232.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'image' => '4-1702300232.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'image' => '1-1702300342.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'product_id' => 6,
                'image' => '2-1702300198.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'image' => '4-1702300198.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'product_id' => 6,
                'image' => '7-1702300311.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'image' => '7-1702301597.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'image' => '7-1702301597.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'image' => '2-1702301913.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'image' => '3-1702301913.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'image' => '4-1702301913.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'image' => '3-1702302422.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'image' => '5-1702302422.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'image' => '6-1702302422.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'image' => '1-1702302730.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'image' => '2-1702302730.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'image' => '5-1702302730.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'image' => '1-1702303074.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'image' => '2-1702303074.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'image' => '5-1702303074.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'image' => '6-1702311850.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'image' => '8-1702311850.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'image' => '3-1702311850.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'image' => '4-1702312154.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'image' => '8-1702312154.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'image' => '1-1702366330.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'image' => '2-1702366330.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'image' => '3-1702366330.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        if (ProductGallery::count() == 0) {
            ProductGallery::insert($galleries);
        }

    }
}
